declare type AddToHomeParams = {
    url: string;
    appName: string;
    image?: string;
    appId: string;
    icon?: string;
};
declare type AddPhoneContact = {
    photoFilePath: string;
    nickName: string;
    lastName: string;
    middleName: string;
    firstName: string;
    remark: string;
    mobilePhoneNumber: string;
    homePhoneNumber: string;
    workPhoneNumber: string;
    homeFaxNumber: string;
    workFaxNumber: string;
    hostNumber: string;
    addressCountry: string;
    addressState: string;
    addressCity: string;
    addressStreet: string;
    addressPostalCode: string;
    workAddressCountry: string;
    workAddressState: string;
    workAddressCity: string;
    workAddressStreet: string;
    workAddressPostalCode: string;
    homeAddressCountry: string;
    homeAddressState: string;
    homeAddressCity: string;
    homeAddressStreet: string;
    homeAddressPostalCode: string;
    organization: string;
    title: string;
    email: string;
    url: string;
};
declare type TboxCommonsType = {
    measure(options: Array<any>): Promise<Array<number>>;
    addToHome(option: AddToHomeParams): Promise<Array<number>>;
};
declare type TboxContactsType = {
    openContactForm(options: AddPhoneContact): Promise<Array<number>>;
    addToExistingContact(option: AddPhoneContact): Promise<Array<number>>;
};
declare const _default: TboxCommonsType;
export default _default;
export declare const TboxContacts: TboxContactsType;
